
"use client"

import { ArrowRight, Building2, CalendarCheck2, Check, FileCheck2, Mail, Network, Radar, Search, Target } from "lucide-react"
import { AnimatePresence, motion, useMotionValueEvent, useScroll } from "framer-motion"
import { useEffect, useRef, useState, useSyncExternalStore, type ReactNode } from "react"
import { Button } from "@/components/ui/button"
import { cn } from "@/lib/utils"

const EASE = [0.22, 1, 0.36, 1] as const
const subscribe=(fn:()=>void)=>{const media=window.matchMedia("(prefers-reduced-motion: reduce)");media.addEventListener("change",fn);return()=>media.removeEventListener("change",fn)}
const snapshot=()=>window.matchMedia("(prefers-reduced-motion: reduce)").matches
const useReduced=()=>useSyncExternalStore(subscribe,snapshot,()=>false)
const Label=({children,dark=true}:{children:ReactNode;dark?:boolean})=><p className={cn("text-[8px] font-medium uppercase tracking-[0.15em]",dark?"text-white/40":"text-faint")}>{children}</p>
function PlatformHero(){const reduced=useReduced();return <section className="relative overflow-hidden border-b border-black/10 bg-canvas"><div aria-hidden className="absolute inset-x-0 top-0 h-[72%]" style={{backgroundImage:"radial-gradient(circle, rgba(40,20,20,.075) 1px, transparent 1.7px)",backgroundSize:"10px 10px",maskImage:"linear-gradient(to bottom,black,transparent 92%)"}}/><div className="site-container relative flex min-h-[620px] items-center justify-center pb-16 pt-28 lg:min-h-[690px] xl:max-w-[88rem]"><motion.div initial={reduced?false:{opacity:0,y:34}} animate={{opacity:1,y:0}} transition={{duration:.82,ease:EASE}} className="mx-auto max-w-[58rem] text-center"><motion.p initial={reduced?false:{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{duration:.7,ease:EASE}} className="text-[11px] font-medium uppercase tracking-[.18em] text-brand">● &nbsp; Platform</motion.p><h1 className="mt-5 text-[44px] font-medium leading-[.98] tracking-[-.04em] text-heading sm:text-[58px] lg:text-[68px]">{["From a cold account","to a qualified conversation."].map((line,i)=><motion.span key={line} initial={reduced?false:{opacity:0,y:28}} animate={{opacity:1,y:0}} transition={{duration:.78,delay:.1+i*.1,ease:EASE}} className="block">{line}</motion.span>)}</h1><motion.p initial={reduced?false:{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{duration:.72,delay:.3,ease:EASE}} className="mx-auto mt-6 max-w-[46rem] text-[16px] leading-[1.7] text-muted sm:text-[17px]">Oraami researches the right companies, identifies buying signals, maps decision-makers, matches relevant proof, and builds personalised trust—automatically.</motion.p><motion.div initial={reduced?false:{opacity:0,y:22}} animate={{opacity:1,y:0}} transition={{duration:.7,delay:.42,ease:EASE}} className="mt-7 flex flex-wrap justify-center gap-3"><Button href="#platform-workflow" variant="primary" size="lg" icon={ArrowRight}>Explore the platform</Button><Button href="/contact" variant="outline" size="lg">Book a call</Button></motion.div><motion.p initial={reduced?false:{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{duration:.68,delay:.54,ease:EASE}} className="mt-7 text-[10px] uppercase tracking-[.16em] text-faint">Research <b className="px-1 text-brand">→</b> Prioritise <b className="px-1 text-brand">→</b> Personalise <b className="px-1 text-brand">→</b> Engage</motion.p></motion.div></div></section>}

const OPERATIONS = [
  { label:"Account added", detail:"Northfield entered the queue", icon:Building2 },
  { label:"Research started", detail:"8 sources being verified", icon:Search },
  { label:"Signal detected", detail:"Funding and GTM hiring", icon:Radar },
  { label:"Stakeholders found", detail:"6 buying roles mapped", icon:Network },
  { label:"Message approved", detail:"Quality score 96", icon:FileCheck2 },
  { label:"Reply received", detail:"Technical lead requested", icon:Mail },
  { label:"Meeting booked", detail:"Tuesday at 10:30 AM", icon:CalendarCheck2 },
] as const

function OperationRail({ phase, reduced, onSelect }:{phase:number;reduced:boolean;onSelect?:(index:number)=>void}){
  return <div className="relative overflow-x-auto pb-1 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden"><div className="relative grid min-w-[720px] grid-cols-7 gap-2"><div className="absolute left-[7%] right-[7%] top-[17px] h-px bg-white/10"/><motion.div className="absolute left-[7%] top-[17px] h-px origin-left bg-brand" animate={{ width: String(phase / 6 * 86) + "%" }} transition={{duration:reduced?0:.65,ease:EASE}}/>{OPERATIONS.map((item,index)=>{const Icon=item.icon,done=index<=phase;return <button key={item.label} type="button" onClick={()=>onSelect?.(index)} disabled={!onSelect} className="relative z-10 flex flex-col items-center text-center outline-none focus-visible:ring-2 focus-visible:ring-brand"><motion.span animate={{scale:index===phase&&!reduced?[1,1.08,1]:1}} transition={{duration:1.6,repeat:index===phase?Infinity:0}} className={cn("flex h-9 w-9 items-center justify-center rounded-xl border",done?"border-brand/45 bg-brand text-white":"border-white/10 bg-white/[.06] text-white/35")}><Icon className="h-4 w-4"/></motion.span><span className={cn("mt-2 text-[8px] font-medium",done?"text-white/80":"text-white/30")}>{item.label}</span></button>})}</div></div>
}

function IncomingZone({phase}:{phase:number}){
  const accounts=[["Northfield","B2B SaaS","94"],["Cedar Lane","Services","81"],["Arc Systems","Fintech","76"]] as const
  return <div className="h-full min-h-0 overflow-hidden rounded-[18px] border border-white/10 bg-white/[.045] p-3"><div className="flex items-center justify-between"><Label>Incoming accounts</Label><span className="rounded-full bg-white/[.06] px-2 py-1 text-[7px] text-white/45">{phase<1?"3 queued":"2 queued"}</span></div><div className="mt-3 space-y-2">{accounts.map(([name,type,score],index)=><motion.div key={name} animate={{opacity:index===0&&phase>0?.35:1,x:index===0&&phase>0?6:0,scale:index===0&&phase>0?.97:1}} className={cn("rounded-[13px] border p-2.5",index===0?"border-brand/35 bg-brand/10":"border-white/[.08] bg-white/[.03]")}><div className="flex items-center gap-2"><span className="flex h-7 w-7 items-center justify-center rounded-lg bg-white text-[9px] font-bold text-oraami-accent-secondary">{name[0]}</span><span className="min-w-0 flex-1"><span className="block truncate text-[9px] font-medium text-white/75">{name}</span><span className="text-[7px] text-white/35">{type}</span></span><span className="text-[9px] text-brand">{score}%</span></div></motion.div>)}</div><div className="mt-3 rounded-xl border border-dashed border-white/10 px-3 py-2 text-center text-[7px] text-white/30">Quality-first queue · 50 account cap</div></div>
}

function AccountCore({phase,reduced}:{phase:number;reduced:boolean}){
  const fields=[["Industry","B2B software"],["Employees","146"],["Geography","UK + EU"],["Technology","HubSpot"]] as const
  return <div className="relative overflow-hidden rounded-[18px] border border-white/10 bg-white/[.045] p-2">
    {phase===1&&!reduced&&<motion.div aria-hidden initial={{left:"-18%"}} animate={{left:"112%"}} transition={{duration:1.15,ease:EASE}} className="absolute inset-y-0 z-20 w-16 bg-[linear-gradient(90deg,transparent,rgba(245,73,0,.22),transparent)]"/>}
    <div className="flex items-center gap-2.5 border-b border-white/10 pb-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-white text-[13px] font-bold text-oraami-accent-secondary">N</span><div className="min-w-0 flex-1"><p className="text-[12px] font-medium">Northfield</p><p className="text-[8px] text-white/40">Active account operation</p></div><div className="text-right"><p className="text-[19px] font-medium text-brand">{phase<1?"—":"94%"}</p><Label>ICP fit</Label></div></div>
    <div className="mt-1.5 grid grid-cols-2 gap-2">{fields.map(([label,value],index)=><motion.div key={label} animate={{opacity:phase>=1?1:.2,y:phase>=1?0:5}} transition={{delay:index*.06}} className="rounded-xl bg-white/[.04] p-1.5"><Label>{label}</Label><p className="mt-1 text-[8px] text-white/70">{phase>=1?value:"Researching…"}</p></motion.div>)}</div>
    <div className="mt-2 grid grid-cols-2 gap-2"><motion.div animate={{borderColor:phase>=2?"rgba(245,73,0,.45)":"rgba(255,255,255,.08)"}} className="rounded-xl border bg-white/[.035] p-2"><div className="flex items-center gap-2"><Radar className={cn("h-4 w-4",phase>=2?"text-brand":"text-white/25")}/><div><Label>Buying signals</Label><p className={cn("mt-1 text-[8px]",phase>=2?"text-brand":"text-white/30")}>{phase>=2?"2 strong signals":"Monitoring"}</p></div></div></motion.div><motion.div animate={{borderColor:phase>=3?"rgba(245,73,0,.45)":"rgba(255,255,255,.08)"}} className="rounded-xl border bg-white/[.035] p-2"><div className="flex items-center gap-2"><Network className={cn("h-4 w-4",phase>=3?"text-brand":"text-white/25")}/><div><Label>Buying group</Label><p className={cn("mt-1 text-[8px]",phase>=3?"text-brand":"text-white/30")}>{phase>=3?"6 roles mapped":"Not mapped"}</p></div></div></motion.div></div>
    <AnimatePresence>{phase>=2&&<motion.div initial={reduced?false:{opacity:0,y:7}} animate={{opacity:1,y:0}} className="mt-2 flex gap-1.5"><span className="rounded-full bg-brand/15 px-2 py-1 text-[7px] text-brand">{"$12m funding"}</span><span className="rounded-full bg-white/[.06] px-2 py-1 text-[7px] text-white/50">14 GTM roles</span></motion.div>}</AnimatePresence>
  </div>
}

function StakeholderMap({phase,reduced}:{phase:number;reduced:boolean}){
  const nodes=[[42,24,"Founder"],[258,24,"Sales"],[36,102,"Tech"],[264,102,"Finance"]] as const
  return <div className="relative h-full min-h-[128px] rounded-[18px] border border-white/10 bg-white/[.045] p-3"><div className="flex justify-between"><Label>Stakeholder network</Label><span className={cn("text-[7px]",phase>=3?"text-brand":"text-white/30")}>{phase>=3?"6 people found":"Waiting"}</span></div><svg viewBox="0 0 300 125" className="absolute inset-x-3 bottom-1 h-[108px] w-[calc(100%-1.5rem)]" aria-hidden>{["M150 65L42 24","M150 65L258 24","M150 65L36 102","M150 65L264 102"].map((d,index)=><motion.path key={d} d={d} fill="none" stroke={index<2?"#ff4f00":"rgba(255,255,255,.2)"} initial={reduced||phase>=3?{pathLength:1}:{pathLength:0}} animate={{pathLength:phase>=3?1:0}} transition={{duration:.6,delay:index*.07}}/>)}<circle cx="150" cy="65" r="21" fill="#ff4f00" fillOpacity={phase>=3?.16:.04} stroke={phase>=3?"#ff4f00":"rgba(255,255,255,.12)"}/>{nodes.map(([x,y,label],index)=><motion.g key={label} animate={{opacity:phase>=3?1:.2,scale:phase>=3?1:.85}} transition={{delay:index*.07}}><circle cx={x} cy={y} r="16" fill="color-mix(in srgb, var(--color-oraami-accent-secondary) 82%, white)" stroke="rgba(255,255,255,.16)"/><text x={x} y={y+3} fill="white" fillOpacity=".7" textAnchor="middle" fontSize="7">{label}</text></motion.g>)}</svg></div>
}

function CommunicationsZone({phase}:{phase:number}){
  return <div className="grid gap-2 md:grid-cols-[1fr_.82fr]"><motion.div animate={{opacity:phase>=4?1:.35}} className="rounded-[16px] border border-white/10 bg-white/[.045] p-3"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><FileCheck2 className={cn("h-4 w-4",phase>=4?"text-brand":"text-white/25")}/><div><Label>Message preparation</Label><p className="mt-1 text-[9px] text-white/70">Northfield expansion outreach</p></div></div><span className={cn("rounded-full px-2 py-1 text-[7px]",phase>=4?"bg-brand/10 text-brand":"bg-white/[.05] text-white/30")}>{phase>=4?"APPROVED · 96":"DRAFT"}</span></div><div className="mt-2 flex gap-1.5">{["Relevance","Proof","Tone","Timing"].map((x,index)=><motion.span key={x} initial={false} animate={{opacity:phase>=4?1:.25}} transition={{delay:index*.05}} className="rounded-lg bg-white/[.04] px-2 py-1 text-[7px] text-white/50"><Check className="mr-1 inline h-3 w-3 text-brand"/>{x}</motion.span>)}</div></motion.div><motion.div animate={{borderColor:phase>=5?"rgba(245,73,0,.35)":"rgba(255,255,255,.1)"}} className="rounded-[16px] border bg-white/[.045] p-3"><div className="flex items-start gap-2"><Mail className={cn("mt-0.5 h-4 w-4",phase>=5?"text-brand":"text-white/25")}/><div><Label>Latest reply</Label><p className={cn("mt-1 text-[8px] leading-relaxed",phase>=5?"text-white/65":"text-white/25")}>{phase>=5?"This is timely. Can our technical lead join Tuesday?":"Awaiting engagement"}</p></div></div></motion.div></div>
}

function ActivityZone({phase,reduced}:{phase:number;reduced:boolean}){
  const metrics=[["Accounts active",String(38+phase*4)],["Signals today",String(7+Math.min(phase,2)*5)],["Replies",String(Math.max(0,phase-4))]]
  return <div className="flex h-full min-h-0 flex-col gap-2.5"><div className="grid grid-cols-3 gap-1.5">{metrics.map(([label,value],index)=><motion.div key={label} initial={reduced?false:{opacity:0,y:5}} animate={{opacity:1,y:0}} transition={{delay:index*.06}} className="rounded-xl border border-white/[.08] bg-white/[.04] p-2"><Label>{label}</Label><p className="mt-1 text-[13px] font-medium text-white/80">{value}</p></motion.div>)}</div><div className="min-h-0 flex-1 overflow-hidden rounded-[18px] border border-white/10 bg-white/[.045] p-3"><div className="flex justify-between"><Label>Live activity</Label><span className="flex items-center gap-1 text-[7px] text-brand"><span className="h-1.5 w-1.5 rounded-full bg-brand"/> LIVE</span></div><div className="mt-3 space-y-2">{OPERATIONS.slice(0,phase+1).slice(-4).reverse().map((item)=>{const Icon=item.icon;return <motion.div key={item.label} initial={reduced?false:{opacity:0,x:7}} animate={{opacity:1,x:0}} className="flex gap-2 rounded-xl bg-white/[.035] p-2"><span className="flex h-7 w-7 items-center justify-center rounded-lg bg-brand/10 text-brand"><Icon className="h-3.5 w-3.5"/></span><span className="min-w-0"><span className="block text-[8px] font-medium text-white/70">{item.label}</span><span className="block truncate text-[7px] text-white/35">{item.detail}</span></span></motion.div>})}</div></div><AnimatePresence>{phase>=6&&<motion.div initial={reduced?false:{opacity:0,scale:.96,y:8}} animate={{opacity:1,scale:1,y:0}} className="rounded-[16px] border border-brand/30 bg-brand/[.08] p-3"><div className="flex items-center gap-2.5"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-brand/10 text-brand"><CalendarCheck2 className="h-5 w-5"/></span><div><Label>Tuesday · 10:30 AM</Label><p className="mt-1 text-[10px] font-medium text-brand">Qualified meeting booked</p><p className="text-[7px] text-white/35">Alex + Technical lead</p></div></div></motion.div>}</AnimatePresence></div>
}

function MissionWorkspace({phase,reduced,onSelect}:{phase:number;reduced:boolean;onSelect?:(index:number)=>void}){
  return <div className="rounded-[26px] border border-black/[.09] bg-white p-3 shadow-[0_30px_75px_-48px_rgba(30,26,77,.55)] sm:p-4"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-black/[.07] px-1 pb-3"><div className="flex items-center gap-2.5"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-oraami-accent-secondary text-white"><Target className="h-4 w-4"/></span><div><p className="text-[12px] font-medium text-heading">Oraami Mission Control</p><p className="text-[8px] text-faint">Live account operation · Sample workspace</p></div></div><div className="flex items-center gap-3"><span className="flex items-center gap-1.5 text-[8px] font-medium text-brand"><span className="h-2 w-2 rounded-full bg-brand"/> SYSTEM ACTIVE</span><span className="text-[9px] font-semibold text-muted">{String(phase+1).padStart(2,"0")} / 07</span></div></div><div className="mt-3 overflow-hidden rounded-[21px] bg-oraami-accent-secondary p-3 text-white sm:p-4 lg:h-[512px]"><OperationRail phase={phase} reduced={reduced} onSelect={onSelect}/><div className="mt-4 grid gap-3 lg:h-[388px] lg:grid-cols-[190px_minmax(0,1fr)_220px]"><IncomingZone phase={phase}/><div className="grid h-full min-h-0 grid-rows-[minmax(0,1fr)_128px] gap-3"><AccountCore phase={phase} reduced={reduced}/><div className="grid gap-3 md:grid-cols-[.92fr_1.08fr]"><StakeholderMap phase={phase} reduced={reduced}/><CommunicationsZone phase={phase}/></div></div><ActivityZone phase={phase} reduced={reduced}/></div></div></div>
}

function MissionControl(){
  const reduced=useReduced(),track=useRef<HTMLDivElement>(null),[desktop,setDesktop]=useState(false),[phase,setPhase]=useState(0),{scrollYProgress}=useScroll({target:track,offset:["start start","end end"]})
  useEffect(()=>{const media=matchMedia("(min-width: 1024px)"),update=()=>setDesktop(media.matches&&!reduced);update();media.addEventListener("change",update);return()=>media.removeEventListener("change",update)},[reduced])
  useMotionValueEvent(scrollYProgress,"change",value=>{if(!desktop)return;const next=Math.min(6,Math.floor(value*7));setPhase(current=>current===next?current:next)})
  const shown=reduced?6:phase
  const select=(index:number)=>{setPhase(index);if(!desktop||!track.current)return;const top=track.current.getBoundingClientRect().top+scrollY,range=Math.max(track.current.offsetHeight-innerHeight,1);scrollTo({top:top+index/6*range,behavior:reduced?"auto":"smooth"})}
  return <section id="platform-workflow" className="relative overflow-clip border-b border-black/10 bg-canvas-soft"><div ref={track} className={desktop?"h-[285vh]":"h-auto"}>{desktop?<div className="sticky top-16 flex h-[calc(100svh-4rem)] min-h-[680px] flex-col justify-center py-2"><div className="site-container max-w-[90rem]"><div className="mb-3 flex items-end justify-between gap-8"><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-brand">Live operations</p><h2 className="mt-2 text-[32px] font-medium tracking-[-.03em] text-heading">Oraami Mission Control</h2></div><p className="max-w-[32rem] text-right text-[12px] leading-relaxed text-muted">Watch one cold account move through research, signal detection, stakeholder mapping, personalised outreach, and a booked meeting.</p></div><MissionWorkspace phase={shown} reduced={reduced} onSelect={select}/></div></div>:<div className="site-container py-16"><div className="mx-auto max-w-2xl text-center"><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-brand">Live operations</p><h2 className="mt-3 text-[34px] font-medium tracking-[-.035em] text-heading">Oraami Mission Control</h2><p className="mt-4 text-[14px] leading-relaxed text-muted">Watch one cold account move through research, signal detection, stakeholder mapping, personalised outreach, and a booked meeting.</p></div><div className="mt-8"><MissionWorkspace phase={shown} reduced={reduced} onSelect={reduced?undefined:setPhase}/></div>{!reduced&&<div className="mt-5 flex justify-center gap-3"><button type="button" disabled={phase===0} onClick={()=>setPhase(value=>Math.max(0,value-1))} className="rounded-xl border border-black/10 bg-white px-4 py-2.5 text-[11px] font-medium text-heading disabled:opacity-35">Previous state</button><button type="button" disabled={phase===6} onClick={()=>setPhase(value=>Math.min(6,value+1))} className="rounded-xl bg-brand px-4 py-2.5 text-[11px] font-medium text-white disabled:opacity-35">Advance operation</button></div>}</div>}</div></section>
}

export default function PlatformPageClient(){return <><PlatformHero/><MissionControl/></>}
